name: Android CI

on:
  push:
    branches: [ master ]
  

jobs:
  build:
   runs-on: ubuntu-latest
   steps:
            
     - uses: actions/checkout@v2
     

     - name: Setup Java
       uses: actions/setup-java@v2
       with:
        distribution: 'adopt'
        java-version: '11'
     - name: Setup sonarqube
       uses: warchant/setup-sonar-scanner@v3
     
     - uses: actions/checkout@master
     - name: SonarQube Scan
       uses: kitabisa/sonarqube-action@v1.1.0
       with:
        host: ${{ secrets.SONARQUBE_HOST }}
        login: ${{ secrets.SONARQUBE_TOKEN }}
        projectKey: demo
        projectName: demo
