name: Android CI

on:
  push:
    branches: [ master ]
  

jobs:
  build:
   runs-on: ubuntu-latest
   steps:
            
     - uses: actions/checkout@v2
     

     - name: Setup Java
       uses: actions/setup-java@v2
       with:
        distribution: 'adopt'
        java-version: '11'
     - name: Setup sonarqube
       uses: warchant/setup-sonar-scanner@v3
     - name: Run sonarqube

       run: sonar-scanner
         -Dsonar.login=${{ secrets.SONARQUBE_TOKEN }}
         -Dsonar.host.url=${{ secrets.SONARQUBE_HOST}}
         -Dsonar.projectKey=demo
         -Dsonar.projectName=demo
         
     - name: Build with gradle
       run: ./gradlew build
       
     - name: Upload apk
       uses: actions/upload-artifact@v2.1.4
       with:
        name: app
        path: app/build/outputs/apk/debug/app-debug.apk
